# -*- coding: utf-8 -*-
"""ProjectCard-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A3llhX6AuJaASxfAUGoyjfMFycdWBIYv

In the Draw a Card project I'll create a virtual deck of cards. Shuffle them and then display them one by one using ASCII art. :):D  ☕
"""

import random
# Define the values and suits for the deck of cards
values = ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A']
suits = ['♠', '♥', '♦', '♣']

# Create the deck by combining values and suits
deck = [f"{value} of {suit}" for value in values for suit in suits]
def ascii_card(card):
    value, suit = card.split(' of ')
    card_art = f"""
    _________
   |{value:<2}       |
   |         |
   |    {suit}    |
   |         |
   |       {value:>2}|
    ---------
    """
    return card_art
def shuffle_deck(deck):
    random.shuffle(deck)
def draw_card(deck):
    if deck:
        card = deck.pop()
        print(ascii_card(card))
        print(f"Card drawn: {card}")
    else:
        print("No more cards in the deck.")
def main():
    shuffle_deck(deck)
    while True:
        user_input = input("\nPress 'd' to draw a card, 'q' to quit: ").lower()
        if user_input == 'd':
            draw_card(deck)
        elif user_input == 'q':
            print("Thanks for playing!")
            break
        else:
            print("Invalid input. Please press 'd' to draw or 'q' to quit.")

if __name__ == "__main__":
    main()

